# Generated by Django 5.2.4 on 2025-07-13 03:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Task title (max 250 charcaters)', max_length=250, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Optional task description', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether task is completed')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='Priority task level', max_length=6)),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional due date for the task', null=True)),
                ('category', models.CharField(blank=True, help_text='Optional category/tag for the task', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'completed'], name='tasks_task_user_id_f226ed_idx'), models.Index(fields=['user', 'priority'], name='tasks_task_user_id_13ec9e_idx'), models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx')],
            },
        ),
    ]
